### ISSUE TITLE
نمایش اعداد بصورت فارسی

### ISSUE THREAD

**Issue by aliebrahimi2015** [VahidN/KendoUI.Core.Samples#1]
بهترین روش برای نمایش اعداد انگللیسی به فارسی در این گرید بچصورت هست؟
متشکرم

**Comment by VahidN** [comment]
<div dir="rtl">

از نكته‌ي «[فرمت تاریخ میلادی به شمسی در حین نمایش](http://www.dotnettips.info/post/1909/%d9%81%d8%b1%d9%85%d8%aa-%da%a9%d8%b1%d8%af%d9%86-%d8%a7%d8%b7%d9%84%d8%a7%d8%b9%d8%a7%d8%aa-%d9%86%d9%85%d8%a7%db%8c%d8%b4-%d8%af%d8%a7%d8%af%d9%87-%d8%b4%d8%af%d9%87-%d8%a8%d9%87-%da%a9%d9%85%da%a9-kendo-ui-grid)» ايده بگيريد
