### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by mammadkoma** [VahidN/KendoUI.Core.Samples#2]
"Kendo.DynamicLinq.Core" builded correctly but "KendoUI.Core.Samples" does not build.
(Win 10 64bit & VS 2017)

1>------ Build started: Project: KendoUI.Core.Samples, Configuration: Debug Any CPU ------
1>It was not possible to find any compatible framework version
1>
1>The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
1>
1>  - Check application dependencies and target a framework version installed at:
1>
1>      \
1>
1>  - Alternatively, install the framework version '1.0.0'.
1>
1>E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj(1602,5): error MSB3073: The command "dotnet bundle" exited with code -2147450749.
1>Done building project "KendoUI.Core.Samples.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by VahidN** [comment]
I think you are using an outdated version of VS2017. To prove that, just run the [_1-dotnet_run.bat](https://github.com/VahidN/KendoUI.Core.Samples/blob/master/src/KendoUI.Core.Samples/_1-dotnet_run.bat) file (double click). You will see it works fine, without any errors.
```
dotnet restore
dotnet watch run
```
You have 2 choices here:
- Update your VS 2017
- Or remove it from your system (because its old/not updated build system will cause problems for VSCode) and [start using VSCode](http://www.dotnettips.info/learningpaths/details/60).

**Comment by mammadkoma** [comment]
No I have the latest VS 2017. I think your asp.net core is not v2.
My VS:
Microsoft Visual Studio Enterprise 2017 
Version 15.5.1
VisualStudio.15.Release/15.5.1+27130.2003
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual Basic 2017   00369-90000-00000-AA417
Microsoft Visual Basic 2017

Visual C# 2017   00369-90000-00000-AA417
Microsoft Visual C# 2017

Visual F# 4.1   00369-90000-00000-AA417
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31125.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

*******************************************************************************************************
I ran "_1-dotnet_run" and its result:
E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>dotnet watch run
watch : Started
E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj(1602,5): error MSB3073: The command "dotnet bundle" exited with code -2147450749.

The build failed. Please fix the build errors and run again.
watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...

**Comment by VahidN** [comment]
OK. You have problems running `dotnet bundle` command. To fix it, open the command prompt and then navigate to `src\KendoUI.Core.Samples` path, finally run the following commands, one by one:
```
dotnet restore
npm install
npm install -g bower
bower install
```
Now you can run
```
dotnet watch run
```

**Comment by mammadkoma** [comment]
PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples> dotnet restore
  Restore completed in 37.28 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 15.92 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\Kendo.DynamicLinq.Core\Kendo.DynamicLinq.Core.csproj.
  Restore completed in 56.12 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 62.16 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 57.49 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>




PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples> npm install
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples> npm install -g bower
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ npm install -g bower
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples> bower install
bower : The term 'bower' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ bower install
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (bower:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>

**Comment by VahidN** [comment]
npm needs node.js, so you should install it too https://nodejs.org/en/download/current/

**Comment by mammadkoma** [comment]
I installed node-v9.5.0-x64 but:
PS E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples> npm install
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by VahidN** [comment]
Yes. Npm is not a `cmdlet`, so don't use the `NuGet power-shell command` to run it. Use the command prompt of the OS, outside of the VS.

**Comment by mammadkoma** [comment]
In command prompt:
E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>dotnet restore
  Restore completed in 37.02 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 48.59 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 57.47 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.
  Restore completed in 41.05 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\Kendo.DynamicLinq.Core\Kendo.DynamicLinq.Core.csproj.
  Restore completed in 60.88 ms for E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples\KendoUI.Core.Samples.csproj.

E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.125s

E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>npm install -g bower
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\SOFT\AppData\Roaming\npm\bower -> C:\Users\SOFT\AppData\Roaming\npm\node_modules\bower\bin\bower
+ bower@1.8.2
added 1 package in 12.096s

E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>bower install

E:\Learning\DotNetTips\KendoUI.Core.Samples-master\src\KendoUI.Core.Samples>

********************************************************************************************
And steel error : The command "dotnet bundle" exited with code -2147450749.

**Comment by VahidN** [comment]
- just delete the `package-lock.json` file, if you have it.
- update the `BundlerMinifier.Core` package to [v 2.6.362](https://github.com/VahidN/KendoUI.Core.Samples/blob/master/src/KendoUI.Core.Samples/KendoUI.Core.Samples.csproj#L13)
```
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.6.362" />
```

**Comment by mammadkoma** [comment]
Thank you my sir.
