### ISSUE TITLE
نمایش تاریخ شمسی ندارد

### ISSUE THREAD

**Issue by Kavan1365** [VahidN/KendoUI.Core.Samples#5]
امکانش هست تاریخ شمسی نمایش بده 

![Untitled](https://user-images.githubusercontent.com/31569602/82611161-22a80f00-9bd5-11ea-8282-34addde63fcf.png)

**Comment by VahidN** [comment]
[اينجا](https://www.dotnettips.info/post/2741/%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%d8%a7%d9%81%d8%b2%d9%88%d9%86%d9%87-md-bootstrappersiandatetimepicker-%d8%af%d8%b1-%da%af%d8%b1%db%8c%d8%af%d9%87%d8%a7%db%8c-kendo-ui)
